!------------------------------------------------------------------------
&tao_start
  plot_file = 'tao_plot.init'
/
!------------------------------------------------------------------------
&tao_design_lattice
   n_universes = 1
   design_lattice(1)%file = 'fodo.bmad'
/
!------------------------------------------------------------------------
&tao_params
!   global%rf_on    = F
    global%track_type = "beam"
/
!------------------------------------------------------------------------
&tao_beam_init
   beam_init%n_particle = 10000
   ix_universe          = 1
   beam_init%n_bunch    = 1
   beam_init%a_emit     = 1.E-6
   beam_init%b_emit     = 1.E-6
   beam_init%sig_e      = 1.E-3
   beam_init%sig_z      = 10.E-3
   beam_init%bunch_charge = 1.6E-14
/
alias rrr rei tao
